import Head from 'next/head'
import Navbar from '../components/navbar'
import HomeBanner from '../components/sections/homebanner'
import About from '../components/sections/about'
import Work from '../components/sections/work'

const Home = () => {
  

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex flex-col bg-white'>
        <Navbar />
        <HomeBanner />
        <About />
        <Work/>
      </main>

      <footer>
      </footer>
    </div>
  )
}

export default Home
